import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Template definitions
const templates = [
  // ================== PROFESSIONAL CATEGORY (10 templates) ==================
  {
    slug: "corporate-classic",
    name: "Corporate Classic",
    description: "Traditional corporate resume with clean, professional layout",
    category: "professional",
    sortOrder: 1,
    structure: {
      layout: "single-column",
      sections: ["basics", "summary", "work", "education", "skills"],
      sectionOrder: ["basics", "summary", "work", "education", "skills"],
      showAvatar: true,
      spacing: "comfortable",
    },
    theme: {
      primaryColor: "#1a365d",
      secondaryColor: "#2c5282",
      accentColor: "#3182ce",
      textColor: "#1a202c",
      backgroundColor: "#ffffff",
      fontFamily: "Georgia, serif",
      headingFont: "Arial, sans-serif",
      fontSize: "11pt",
      lineHeight: 1.6,
    },
  },
  {
    slug: "executive-profile",
    name: "Executive Profile",
    description: "Senior-level professional template with emphasis on leadership",
    category: "professional",
    sortOrder: 2,
    structure: {
      layout: "two-column",
      sections: ["basics", "summary", "work", "education", "skills", "certifications"],
      sectionOrder: ["basics", "summary", "work", "education", "skills", "certifications"],
      showAvatar: true,
      spacing: "compact",
    },
    theme: {
      primaryColor: "#2d3748",
      secondaryColor: "#4a5568",
      accentColor: "#718096",
      textColor: "#1a202c",
      backgroundColor: "#ffffff",
      fontFamily: "Times New Roman, serif",
      headingFont: "Helvetica, sans-serif",
      fontSize: "10pt",
      lineHeight: 1.5,
    },
  },
  {
    slug: "business-professional",
    name: "Business Professional",
    description: "Modern business template with subtle elegance",
    category: "professional",
    sortOrder: 3,
    structure: {
      layout: "single-column",
      sections: ["basics", "work", "education", "skills", "languages"],
      sectionOrder: ["basics", "work", "education", "skills", "languages"],
      showAvatar: false,
      spacing: "comfortable",
    },
    theme: {
      primaryColor: "#2b6cb0",
      secondaryColor: "#3182ce",
      accentColor: "#4299e1",
      textColor: "#2d3748",
      backgroundColor: "#ffffff",
      fontFamily: "Calibri, sans-serif",
      headingFont: "Calibri, sans-serif",
      fontSize: "11pt",
      lineHeight: 1.6,
    },
  },
  {
    slug: "financial-analyst",
    name: "Financial Analyst",
    description: "Conservative template perfect for finance and banking roles",
    category: "professional",
    sortOrder: 4,
    structure: {
      layout: "single-column",
      sections: ["basics", "summary", "work", "education", "certifications", "skills"],
      sectionOrder: ["basics", "summary", "work", "education", "certifications", "skills"],
      showAvatar: false,
      spacing: "comfortable",
    },
    theme: {
      primaryColor: "#1e3a8a",
      secondaryColor: "#1e40af",
      accentColor: "#3b82f6",
      textColor: "#1f2937",
      backgroundColor: "#ffffff",
      fontFamily: "Times New Roman, serif",
      headingFont: "Arial, sans-serif",
      fontSize: "11pt",
      lineHeight: 1.65,
    },
  },
  {
    slug: "legal-professional",
    name: "Legal Professional",
    description: "Formal template designed for legal and law careers",
    category: "professional",
    sortOrder: 5,
    structure: {
      layout: "single-column",
      sections: ["basics", "summary", "education", "work", "publications", "skills"],
      sectionOrder: ["basics", "summary", "education", "work", "publications", "skills"],
      showAvatar: false,
      spacing: "comfortable",
    },
    theme: {
      primaryColor: "#0f172a",
      secondaryColor: "#1e293b",
      accentColor: "#334155",
      textColor: "#0f172a",
      backgroundColor: "#ffffff",
      fontFamily: "Garamond, serif",
      headingFont: "Georgia, serif",
      fontSize: "11pt",
      lineHeight: 1.7,
    },
  },
  {
    slug: "healthcare-professional",
    name: "Healthcare Professional",
    description: "Clean medical and healthcare industry template",
    category: "professional",
    sortOrder: 6,
    structure: {
      layout: "single-column",
      sections: ["basics", "summary", "work", "education", "certifications", "skills"],
      sectionOrder: ["basics", "summary", "work", "education", "certifications", "skills"],
      showAvatar: true,
      spacing: "comfortable",
    },
    theme: {
      primaryColor: "#065f46",
      secondaryColor: "#047857",
      accentColor: "#10b981",
      textColor: "#1f2937",
      backgroundColor: "#ffffff",
      fontFamily: "Arial, sans-serif",
      headingFont: "Arial, sans-serif",
      fontSize: "11pt",
      lineHeight: 1.6,
    },
  },
  {
    slug: "academic-cv",
    name: "Academic CV",
    description: "Comprehensive template for academic and research positions",
    category: "professional",
    sortOrder: 7,
    structure: {
      layout: "single-column",
      sections: ["basics", "summary", "education", "work", "publications", "awards", "skills"],
      sectionOrder: ["basics", "summary", "education", "work", "publications", "awards", "skills"],
      showAvatar: true,
      spacing: "relaxed",
    },
    theme: {
      primaryColor: "#7c2d12",
      secondaryColor: "#9a3412",
      accentColor: "#c2410c",
      textColor: "#1f2937",
      backgroundColor: "#ffffff",
      fontFamily: "Palatino, serif",
      headingFont: "Georgia, serif",
      fontSize: "11pt",
      lineHeight: 1.7,
    },
  },
  {
    slug: "engineering-standard",
    name: "Engineering Standard",
    description: "Technical professional template for engineering roles",
    category: "professional",
    sortOrder: 8,
    structure: {
      layout: "two-column",
      sections: ["basics", "summary", "work", "education", "skills", "projects"],
      sectionOrder: ["basics", "summary", "work", "education", "skills", "projects"],
      showAvatar: false,
      spacing: "comfortable",
    },
    theme: {
      primaryColor: "#1e40af",
      secondaryColor: "#2563eb",
      accentColor: "#3b82f6",
      textColor: "#111827",
      backgroundColor: "#ffffff",
      fontFamily: "Arial, sans-serif",
      headingFont: "Arial, sans-serif",
      fontSize: "10pt",
      lineHeight: 1.5,
    },
  },
  {
    slug: "management-consultant",
    name: "Management Consultant",
    description: "Strategic template for consulting and advisory roles",
    category: "professional",
    sortOrder: 9,
    structure: {
      layout: "single-column",
      sections: ["basics", "summary", "work", "education", "skills", "languages"],
      sectionOrder: ["basics", "summary", "work", "education", "skills", "languages"],
      showAvatar: false,
      spacing: "comfortable",
    },
    theme: {
      primaryColor: "#374151",
      secondaryColor: "#4b5563",
      accentColor: "#6b7280",
      textColor: "#111827",
      backgroundColor: "#ffffff",
      fontFamily: "Helvetica, sans-serif",
      headingFont: "Helvetica, sans-serif",
      fontSize: "11pt",
      lineHeight: 1.6,
    },
  },
  {
    slug: "government-standard",
    name: "Government Standard",
    description: "Formal template suitable for government and public sector",
    category: "professional",
    sortOrder: 10,
    structure: {
      layout: "single-column",
      sections: ["basics", "summary", "work", "education", "certifications", "skills"],
      sectionOrder: ["basics", "summary", "work", "education", "certifications", "skills"],
      showAvatar: false,
      spacing: "relaxed",
    },
    theme: {
      primaryColor: "#1e3a8a",
      secondaryColor: "#1e40af",
      accentColor: "#2563eb",
      textColor: "#111827",
      backgroundColor: "#ffffff",
      fontFamily: "Times New Roman, serif",
      headingFont: "Arial, sans-serif",
      fontSize: "12pt",
      lineHeight: 1.75,
    },
  },

  // ================== CREATIVE CATEGORY (10 templates) ==================
  {
    slug: "bold-innovator",
    name: "Bold Innovator",
    description: "Eye-catching template with vibrant colors and modern design",
    category: "creative",
    sortOrder: 1,
    structure: {
      layout: "two-column-asymmetric",
      sections: ["basics", "summary", "work", "skills", "education", "projects"],
      sectionOrder: ["basics", "summary", "work", "skills", "education", "projects"],
      showAvatar: true,
      spacing: "comfortable",
    },
    theme: {
      primaryColor: "#dc2626",
      secondaryColor: "#ef4444",
      accentColor: "#f87171",
      textColor: "#1f2937",
      backgroundColor: "#ffffff",
      fontFamily: "Roboto, sans-serif",
      headingFont: "Montserrat, sans-serif",
      fontSize: "11pt",
      lineHeight: 1.6,
    },
  },
  {
    slug: "designer-portfolio",
    name: "Designer Portfolio",
    description: "Visual-focused template perfect for designers and creatives",
    category: "creative",
    sortOrder: 2,
    structure: {
      layout: "grid",
      sections: ["basics", "portfolio", "work", "skills", "education"],
      sectionOrder: ["basics", "portfolio", "work", "skills", "education"],
      showAvatar: true,
      spacing: "relaxed",
    },
    theme: {
      primaryColor: "#7c3aed",
      secondaryColor: "#8b5cf6",
      accentColor: "#a78bfa",
      textColor: "#1f2937",
      backgroundColor: "#fafafa",
      fontFamily: "Inter, sans-serif",
      headingFont: "Poppins, sans-serif",
      fontSize: "11pt",
      lineHeight: 1.65,
    },
  },
  {
    slug: "artistic-expression",
    name: "Artistic Expression",
    description: "Unique layout with creative flair for artists and performers",
    category: "creative",
    sortOrder: 3,
    structure: {
      layout: "two-column-asymmetric",
      sections: ["basics", "summary", "portfolio", "work", "education", "skills"],
      sectionOrder: ["basics", "summary", "portfolio", "work", "education", "skills"],
      showAvatar: true,
      spacing: "comfortable",
    },
    theme: {
      primaryColor: "#db2777",
      secondaryColor: "#ec4899",
      accentColor: "#f472b6",
      textColor: "#1f2937",
      backgroundColor: "#ffffff",
      fontFamily: "Open Sans, sans-serif",
      headingFont: "Playfair Display, serif",
      fontSize: "11pt",
      lineHeight: 1.6,
    },
  },
  {
    slug: "media-professional",
    name: "Media Professional",
    description: "Dynamic template for journalism, PR, and media careers",
    category: "creative",
    sortOrder: 4,
    structure: {
      layout: "magazine",
      sections: ["basics", "summary", "work", "publications", "skills", "education"],
      sectionOrder: ["basics", "summary", "work", "publications", "skills", "education"],
      showAvatar: true,
      spacing: "comfortable",
    },
    theme: {
      primaryColor: "#ea580c",
      secondaryColor: "#f97316",
      accentColor: "#fb923c",
      textColor: "#1f2937",
      backgroundColor: "#ffffff",
      fontFamily: "Lato, sans-serif",
      headingFont: "Merriweather, serif",
      fontSize: "11pt",
      lineHeight: 1.6,
    },
  },
  {
    slug: "startup-founder",
    name: "Startup Founder",
    description: "Entrepreneurial template with modern startup vibes",
    category: "creative",
    sortOrder: 5,
    structure: {
      layout: "two-column",
      sections: ["basics", "summary", "work", "projects", "skills", "education"],
      sectionOrder: ["basics", "summary", "work", "projects", "skills", "education"],
      showAvatar: true,
      spacing: "compact",
    },
    theme: {
      primaryColor: "#0891b2",
      secondaryColor: "#06b6d4",
      accentColor: "#22d3ee",
      textColor: "#111827",
      backgroundColor: "#ffffff",
      fontFamily: "Inter, sans-serif",
      headingFont: "Inter, sans-serif",
      fontSize: "10pt",
      lineHeight: 1.5,
    },
  },
  {
    slug: "marketing-maven",
    name: "Marketing Maven",
    description: "Vibrant template showcasing marketing creativity",
    category: "creative",
    sortOrder: 6,
    structure: {
      layout: "two-column-asymmetric",
      sections: ["basics", "summary", "work", "skills", "projects", "education"],
      sectionOrder: ["basics", "summary", "work", "skills", "projects", "education"],
      showAvatar: true,
      spacing: "comfortable",
    },
    theme: {
      primaryColor: "#d946ef",
      secondaryColor: "#e879f9",
      accentColor: "#f0abfc",
      textColor: "#1f2937",
      backgroundColor: "#ffffff",
      fontFamily: "Nunito, sans-serif",
      headingFont: "Raleway, sans-serif",
      fontSize: "11pt",
      lineHeight: 1.6,
    },
  },
  {
    slug: "digital-nomad",
    name: "Digital Nomad",
    description: "Modern template for remote workers and digital professionals",
    category: "creative",
    sortOrder: 7,
    structure: {
      layout: "single-column-modern",
      sections: ["basics", "summary", "skills", "work", "education", "languages"],
      sectionOrder: ["basics", "summary", "skills", "work", "education", "languages"],
      showAvatar: true,
      spacing: "comfortable",
    },
    theme: {
      primaryColor: "#0ea5e9",
      secondaryColor: "#38bdf8",
      accentColor: "#7dd3fc",
      textColor: "#1e293b",
      backgroundColor: "#ffffff",
      fontFamily: "Source Sans Pro, sans-serif",
      headingFont: "Quicksand, sans-serif",
      fontSize: "11pt",
      lineHeight: 1.6,
    },
  },
  {
    slug: "content-creator",
    name: "Content Creator",
    description: "Engaging template for influencers and content professionals",
    category: "creative",
    sortOrder: 8,
    structure: {
      layout: "grid",
      sections: ["basics", "summary", "work", "portfolio", "skills", "awards"],
      sectionOrder: ["basics", "summary", "work", "portfolio", "skills", "awards"],
      showAvatar: true,
      spacing: "relaxed",
    },
    theme: {
      primaryColor: "#f59e0b",
      secondaryColor: "#fbbf24",
      accentColor: "#fcd34d",
      textColor: "#1f2937",
      backgroundColor: "#fffbeb",
      fontFamily: "Rubik, sans-serif",
      headingFont: "Bebas Neue, sans-serif",
      fontSize: "11pt",
      lineHeight: 1.6,
    },
  },
  {
    slug: "ux-ui-specialist",
    name: "UX/UI Specialist",
    description: "Clean modern design showcasing user experience expertise",
    category: "creative",
    sortOrder: 9,
    structure: {
      layout: "two-column",
      sections: ["basics", "summary", "work", "projects", "skills", "education"],
      sectionOrder: ["basics", "summary", "work", "projects", "skills", "education"],
      showAvatar: true,
      spacing: "comfortable",
    },
    theme: {
      primaryColor: "#6366f1",
      secondaryColor: "#818cf8",
      accentColor: "#a5b4fc",
      textColor: "#1e293b",
      backgroundColor: "#f8fafc",
      fontFamily: "Inter, sans-serif",
      headingFont: "Space Grotesk, sans-serif",
      fontSize: "10pt",
      lineHeight: 1.5,
    },
  },
  {
    slug: "brand-strategist",
    name: "Brand Strategist",
    description: "Sophisticated template for branding and strategy professionals",
    category: "creative",
    sortOrder: 10,
    structure: {
      layout: "two-column-asymmetric",
      sections: ["basics", "summary", "work", "skills", "projects", "education"],
      sectionOrder: ["basics", "summary", "work", "skills", "projects", "education"],
      showAvatar: true,
      spacing: "comfortable",
    },
    theme: {
      primaryColor: "#be185d",
      secondaryColor: "#db2777",
      accentColor: "#ec4899",
      textColor: "#1f2937",
      backgroundColor: "#ffffff",
      fontFamily: "Assistant, sans-serif",
      headingFont: "DM Sans, sans-serif",
      fontSize: "11pt",
      lineHeight: 1.6,
    },
  },

  // ================== MINIMAL CATEGORY (10 templates) ==================
  {
    slug: "simple-elegance",
    name: "Simple Elegance",
    description: "Ultra-clean minimal design focusing on content",
    category: "minimal",
    sortOrder: 1,
    structure: {
      layout: "single-column",
      sections: ["basics", "work", "education", "skills"],
      sectionOrder: ["basics", "work", "education", "skills"],
      showAvatar: false,
      spacing: "relaxed",
    },
    theme: {
      primaryColor: "#000000",
      secondaryColor: "#1f2937",
      accentColor: "#4b5563",
      textColor: "#1f2937",
      backgroundColor: "#ffffff",
      fontFamily: "Helvetica, sans-serif",
      headingFont: "Helvetica, sans-serif",
      fontSize: "11pt",
      lineHeight: 1.8,
    },
  },
  {
    slug: "clean-slate",
    name: "Clean Slate",
    description: "Minimalist template with maximum white space",
    category: "minimal",
    sortOrder: 2,
    structure: {
      layout: "single-column",
      sections: ["basics", "summary", "work", "education", "skills"],
      sectionOrder: ["basics", "summary", "work", "education", "skills"],
      showAvatar: false,
      spacing: "relaxed",
    },
    theme: {
      primaryColor: "#18181b",
      secondaryColor: "#27272a",
      accentColor: "#3f3f46",
      textColor: "#18181b",
      backgroundColor: "#ffffff",
      fontFamily: "Arial, sans-serif",
      headingFont: "Arial, sans-serif",
      fontSize: "11pt",
      lineHeight: 1.75,
    },
  },
  {
    slug: "essential-resume",
    name: "Essential Resume",
    description: "Bare essentials with perfect typography",
    category: "minimal",
    sortOrder: 3,
    structure: {
      layout: "single-column",
      sections: ["basics", "work", "education", "skills"],
      sectionOrder: ["basics", "work", "education", "skills"],
      showAvatar: false,
      spacing: "comfortable",
    },
    theme: {
      primaryColor: "#0f172a",
      secondaryColor: "#1e293b",
      accentColor: "#334155",
      textColor: "#0f172a",
      backgroundColor: "#ffffff",
      fontFamily: "Georgia, serif",
      headingFont: "Georgia, serif",
      fontSize: "11pt",
      lineHeight: 1.7,
    },
  },
  {
    slug: "modern-minimal",
    name: "Modern Minimal",
    description: "Contemporary minimal design with subtle accents",
    category: "minimal",
    sortOrder: 4,
    structure: {
      layout: "single-column",
      sections: ["basics", "summary", "work", "education", "skills"],
      sectionOrder: ["basics", "summary", "work", "education", "skills"],
      showAvatar: false,
      spacing: "comfortable",
    },
    theme: {
      primaryColor: "#111827",
      secondaryColor: "#1f2937",
      accentColor: "#374151",
      textColor: "#111827",
      backgroundColor: "#ffffff",
      fontFamily: "Inter, sans-serif",
      headingFont: "Inter, sans-serif",
      fontSize: "11pt",
      lineHeight: 1.6,
    },
  },
  {
    slug: "monochrome",
    name: "Monochrome",
    description: "Black and white simplicity with strong hierarchy",
    category: "minimal",
    sortOrder: 5,
    structure: {
      layout: "single-column",
      sections: ["basics", "work", "education", "skills"],
      sectionOrder: ["basics", "work", "education", "skills"],
      showAvatar: false,
      spacing: "relaxed",
    },
    theme: {
      primaryColor: "#000000",
      secondaryColor: "#262626",
      accentColor: "#525252",
      textColor: "#171717",
      backgroundColor: "#ffffff",
      fontFamily: "Courier New, monospace",
      headingFont: "Courier New, monospace",
      fontSize: "10pt",
      lineHeight: 1.7,
    },
  },
  {
    slug: "whitespace-pro",
    name: "Whitespace Pro",
    description: "Generous spacing creating breathing room",
    category: "minimal",
    sortOrder: 6,
    structure: {
      layout: "single-column",
      sections: ["basics", "work", "education", "skills"],
      sectionOrder: ["basics", "work", "education", "skills"],
      showAvatar: false,
      spacing: "relaxed",
    },
    theme: {
      primaryColor: "#1e293b",
      secondaryColor: "#334155",
      accentColor: "#475569",
      textColor: "#1e293b",
      backgroundColor: "#ffffff",
      fontFamily: "Lato, sans-serif",
      headingFont: "Lato, sans-serif",
      fontSize: "11pt",
      lineHeight: 1.9,
    },
  },
  {
    slug: "swiss-style",
    name: "Swiss Style",
    description: "International typographic style inspired design",
    category: "minimal",
    sortOrder: 7,
    structure: {
      layout: "grid-minimal",
      sections: ["basics", "work", "education", "skills"],
      sectionOrder: ["basics", "work", "education", "skills"],
      showAvatar: false,
      spacing: "comfortable",
    },
    theme: {
      primaryColor: "#000000",
      secondaryColor: "#404040",
      accentColor: "#737373",
      textColor: "#000000",
      backgroundColor: "#ffffff",
      fontFamily: "Helvetica Neue, sans-serif",
      headingFont: "Helvetica Neue, sans-serif",
      fontSize: "10pt",
      lineHeight: 1.6,
    },
  },
  {
    slug: "refined-simplicity",
    name: "Refined Simplicity",
    description: "Sophisticated minimal approach with subtle details",
    category: "minimal",
    sortOrder: 8,
    structure: {
      layout: "single-column",
      sections: ["basics", "summary", "work", "education", "skills"],
      sectionOrder: ["basics", "summary", "work", "education", "skills"],
      showAvatar: false,
      spacing: "comfortable",
    },
    theme: {
      primaryColor: "#0c4a6e",
      secondaryColor: "#075985",
      accentColor: "#0369a1",
      textColor: "#0f172a",
      backgroundColor: "#ffffff",
      fontFamily: "Source Sans Pro, sans-serif",
      headingFont: "Source Sans Pro, sans-serif",
      fontSize: "11pt",
      lineHeight: 1.65,
    },
  },
  {
    slug: "clarity-focus",
    name: "Clarity Focus",
    description: "Maximum readability with clear visual hierarchy",
    category: "minimal",
    sortOrder: 9,
    structure: {
      layout: "single-column",
      sections: ["basics", "work", "education", "skills"],
      sectionOrder: ["basics", "work", "education", "skills"],
      showAvatar: false,
      spacing: "comfortable",
    },
    theme: {
      primaryColor: "#1e40af",
      secondaryColor: "#1e3a8a",
      accentColor: "#1d4ed8",
      textColor: "#111827",
      backgroundColor: "#ffffff",
      fontFamily: "Roboto, sans-serif",
      headingFont: "Roboto, sans-serif",
      fontSize: "11pt",
      lineHeight: 1.6,
    },
  },
  {
    slug: "minimalist-pro",
    name: "Minimalist Pro",
    description: "Professional minimal design for any industry",
    category: "minimal",
    sortOrder: 10,
    structure: {
      layout: "single-column",
      sections: ["basics", "summary", "work", "education", "skills"],
      sectionOrder: ["basics", "summary", "work", "education", "skills"],
      showAvatar: false,
      spacing: "comfortable",
    },
    theme: {
      primaryColor: "#1f2937",
      secondaryColor: "#374151",
      accentColor: "#4b5563",
      textColor: "#111827",
      backgroundColor: "#ffffff",
      fontFamily: "System UI, sans-serif",
      headingFont: "System UI, sans-serif",
      fontSize: "11pt",
      lineHeight: 1.6,
    },
  },
];

async function main() {
  console.log("🌱 Seeding database with resume templates...\n");

  let createdCount = 0;
  let updatedCount = 0;

  // Use transaction for atomicity
  await prisma.$transaction(async (tx: any) => {
    for (const template of templates) {
      // @ts-ignore
      const result = await tx.resumeTemplate.upsert({
        where: { name: template.name },
        update: {
          // @ts-ignore
          slug: template.slug,
          description: template.description,
          category: template.category,
          structure: template.structure,
          theme: template.theme,
          sortOrder: template.sortOrder,
          isActive: true,
          isPremium: false,
        },
        create: {
          name: template.name,
          // @ts-ignore
          slug: template.slug,
          description: template.description,
          category: template.category,
          structure: template.structure,
          theme: template.theme,
          sortOrder: template.sortOrder,
          isActive: true,
          isPremium: false,
        },
      });

      if (result.createdAt.getTime() === result.updatedAt.getTime()) {
        createdCount++;
        console.log(`✅ Created: ${template.name} (${template.category})`);
      } else {
        updatedCount++;
        console.log(`🔄 Updated: ${template.name} (${template.category})`);
      }
    }
  });

  console.log("\n" + "=".repeat(50));
  console.log("📊 Seeding Summary:");
  console.log(`   • Total templates: ${templates.length}`);
  console.log(`   • Created: ${createdCount}`);
  console.log(`   • Updated: ${updatedCount}`);
  console.log("=".repeat(50));
  // @ts-ignore
  // Count by category
  const counts = await prisma.resumeTemplate.groupBy({
    by: ["category"],
    _count: true,
  });

  console.log("\n📁 Templates by Category:");
  counts.forEach((count: { category: string; _count: number }) => {
    console.log(`   • ${count.category}: ${count._count}`);
  });

  console.log("\n🎉 Seeding completed successfully!\n");
}

main()
  .catch((e) => {
    console.error("❌ Seeding failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
